server:
  port: 8000
spring:
  application:
    name: gateway
  cloud:
    consul:
      discovery:
        healthCheckInterval: 15s
        hostname: 192.168.7.2
    loadbalancer:
      ribbon: #Netflx impl on maintenance was excluded in the dependencies (pom)
        enabled:false  # was added for readability
      consul:
        enabled: true
        discovery:
          query-passing: true # get only services that are passing health check
    gateway:
      routes:
        - id: multiplication
          uri: lb://multiplication/  # lb means Load Balancer. Before consul http://localhost:8080/
          predicates:
            - Path=/challenges/**,/attempts,/attempts/**,/users/**
        - id: gamification
          uri: lb://gamification/ # lb means Load Balancer. Before consul http://localhost:8081/
          predicates:
            - Path=/leaders
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods:
              - "GET"
              - "POST"
              - "OPTIONS"
      default-filters:
        - name: Retry
          args:
            retries: 3
            methods: GET, POST
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

logging:
  level:
    org.springframework.cloud.gateway.handler.predicate: trace